### ISSUE TITLE
throws error in tlp.keywords

### ISSUE THREAD

**Issue by etcpwd1960** [ministryofpromise/tlp#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\tlp\tlp.py", line 185, in keywords
    raise e
urllib2.URLError: <urlopen error unknown url type: c>

As can see I'm running python 2.7 on Windows
I dont have urllib2 installed I have urllib2 but when I looked at your scripts I couldnt even find a urllib2 call so I thought it must be something in the tlp lib itsself.

**Comment by adamjnichols** [comment]
Hi there -- may I see the code you're calling tlp in please?
